import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  ASSET_ID_PATTERN,
  EXTERNAL_CAS_OBJECT_KEY,
  REPO_PUBLIC_OBJECT_KEY,
  STORAGE_BACKEND_CONTRACTS,
  assetGate,
  findDuplicateJsonKeys,
  isReviewTimestamp,
  isRuntimeResolvable,
  objectKeyFor,
  productionBlockers,
  publicationBlockers,
  publicationReviewBlockers,
  repoPublicObjectKey,
  resolveAssetRefs,
  runtimeAssetUrl,
  validateAssetRegistry,
  type AssetRegistry,
} from "../scripts/spatial/assets.mjs";
import { checkRuntimeAssets, loadSpatialSource, readAssetRegistry } from "../scripts/spatial/cli.mjs";
import { generateSpatialArtifacts, spatialAssetWarnings, validateSpatialSource, type SpatialSourceInput } from "../scripts/spatial/pipeline.mjs";
import { SPATIAL_IMMUTABLE_CACHE_CONTROL, deliveryHeaders, runtimeAssetHeaders } from "../next.config";

/**
 * Runtime asset contract + NRVNAVerse rights / provenance / publication gate
 * (docs/NRVNAVERSE_ASSET_PIPELINE.md).
 *
 * The canonical contract is tested on SYNTHETIC data only: a tiny in-memory registry, a component
 * added to a copy of the real spatial source, and generated bytes written to a temp directory. No
 * vault asset, committed binary or experimental tracer record is involved, and the committed source
 * declares no runtime asset at all.
 */

type Mutable = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any
type Draft = { config: Mutable; scene: Mutable; destinations: Mutable; assets: Mutable };

const APP_ROOT = resolve(__dirname, "..");
const committed = loadSpatialSource() as SpatialSourceInput & { assets?: unknown };

const ID = "ast_fx7k2m9q4w8r3t6y";
const OTHER_ID = "ast_2b4d6f8h0j1k3m5n";
const COMPONENT = "fixture-model";
const BYTES = Buffer.from("glTF synthetic fixture bytes — never a real model");
const SHA = createHash("sha256").update(BYTES).digest("hex");
const KEY = repoPublicObjectKey(ID, SHA, "glb");

const TRACER_REVIEW = { status: "internal-tracer-accepted", reviewedBy: "Fixture Reviewer", reviewedAt: "2026-09-24T10:00:00-07:00" };
const APPROVED_REVIEW = { status: "approved", reviewedBy: "Fixture Reviewer", reviewedAt: "2026-09-24T10:00:00-07:00" };

/**
 * A publishable internal engineering asset: every right explicit, an attributed human
 * `internal-tracer-accepted` review, repo-public bytes (the only publication a repo-public asset may be).
 */
function fixtureAsset(sha = SHA, bytes = BYTES.length, assetId = ID): Mutable {
  return {
    name: "Synthetic contract fixture",
    kind: "model",
    usage: "internal-tracer",
    currentRevision: 1,
    provenance: { origin: "self-authored", creationContext: "original", creator: "NRVNAVerse test suite", dependencies: [] },
    rights: {
      status: "cleared",
      license: "test fixture",
      rightsHolder: "NRVNAVerse",
      attributionRequired: false,
      attributionText: null,
      commercialUse: "allowed",
      webRuntimeRedistribution: "allowed",
      modification: "allowed",
      restrictions: [],
    },
    review: { ...TRACER_REVIEW },
    revisions: {
      "1": { artifact: { sha256: sha, bytes, format: "glb", storage: { backend: "repo-public", objectKey: repoPublicObjectKey(assetId, sha, "glb") } }, stats: { triangles: 12 } },
    },
  };
}

/** The real committed source plus: a registry declared next to the config, and one model in the Hub. */
function source(mutate?: (draft: Draft) => void): SpatialSourceInput {
  const draft = structuredClone({ config: committed.config, scene: committed.scene, destinations: committed.destinations }) as unknown as Draft;
  draft.config.assetRegistry = "asset-registry.json";
  draft.assets = { schemaVersion: 1, assets: { [ID]: fixtureAsset() } };
  draft.scene.components[COMPONENT] = {
    name: "synthetic fixture model",
    id: COMPONENT,
    type: "model",
    kit: "cyber",
    assetRef: ID,
    position: { x: 4, y: 0, z: -10 },
    rotation: { x: 0, y: 0, z: 0 },
    scale: { x: 1, y: 1, z: 1 },
  };
  draft.config.chunks.find((c: Mutable) => c.key === "hub").componentIds.push(COMPONENT);
  mutate?.(draft);
  return draft as unknown as SpatialSourceInput;
}

function codesOf(input: SpatialSourceInput): string[] {
  const result = validateSpatialSource(input);
  return result.ok ? [] : result.errors.map((e) => e.code);
}

function messagesOf(input: SpatialSourceInput): string {
  const result = validateSpatialSource(input);
  return result.ok ? "" : result.errors.map((e) => e.message).join("\n");
}

const asset = (d: Draft, id = ID): Mutable => d.assets.assets[id];
const component = (d: Draft): Mutable => d.scene.components[COMPONENT];

/** Internal tracer whose bytes may be public: cleared, redistributable, accepted for tracing by a named human. */
function asClearedTracer(d: Draft) {
  asset(d).usage = "internal-tracer";
  asset(d).review = { ...TRACER_REVIEW };
}

/** The same asset claimed as production with an attributed approval (production-eligible rights). */
function asProduction(d: Draft) {
  asset(d).usage = "production";
  asset(d).review = { ...APPROVED_REVIEW };
}

describe("committed source — the clean contract ships no runtime asset", () => {
  it("declares no asset registry, references no asset and has no model component", () => {
    expect((committed.config as Mutable).assetRegistry).toBeUndefined();
    expect(committed.assets).toBeUndefined();
    for (const c of Object.values((committed.scene as Mutable).components as Record<string, Mutable>)) {
      expect("assetRef" in c).toBe(false);
      expect(c.type).not.toBe("model");
    }
    expect(generateSpatialArtifacts(committed).assetIds).toEqual([]);
  });

  it("has no repo-public art directory, and the binary check passes on the empty set", () => {
    expect(existsSync(join(APP_ROOT, "public", "assets", "art"))).toBe(false);
    expect(checkRuntimeAssets(null, [])).toEqual({ ok: true, problems: [] });
  });

  it("the synthetic fixture source is valid (the baseline every negative case mutates)", () => {
    expect(validateAssetRegistry(source().assets as unknown)).toEqual([]);
    expect(codesOf(source())).toEqual([]);
    expect(ID).toMatch(ASSET_ID_PATTERN);
  });
});

describe("production rights rule — every right explicit, plus an attributed human approval", () => {
  // The production rule is run on the registry directly: the only backend today is repo-public, which
  // production art may never use, so the full validation always refuses these (repo-public-production).
  const productionCase = (label: string, mutate: (d: Draft) => void, reason: RegExp) =>
    it(label, () => {
      const input = source((d) => {
        asProduction(d);
        mutate(d);
      });
      const gate = assetGate({ components: (input.scene as Mutable).components, registry: input.assets as AssetRegistry });
      expect(gate.errors.map((e) => e.code)).toEqual(["asset-production-unresolved"]);
      expect(gate.errors[0].message).toMatch(reason);
      expect(codesOf(input)).toContain("repo-public-production");
      expect(productionBlockers(asset(input as unknown as Draft)).join("; ")).toMatch(reason);
    });

  it("a fully cleared, approved production asset passes the production rule (its storage is a separate rule)", () => {
    const input = source(asProduction);
    expect(productionBlockers(asset(input as unknown as Draft))).toEqual([]);
    expect(assetGate({ components: (input.scene as Mutable).components, registry: input.assets as AssetRegistry }).errors).toEqual([]);
  });

  productionCase("fails when commercial use is prohibited", (d) => (asset(d).rights.commercialUse = "prohibited"), /commercialUse is "prohibited"/);
  productionCase("fails when commercial use is unknown", (d) => (asset(d).rights.commercialUse = "unknown"), /commercialUse is "unknown"/);
  productionCase("fails when modification is prohibited", (d) => (asset(d).rights.modification = "prohibited"), /modification is "prohibited"/);
  productionCase("fails when modification is unknown", (d) => (asset(d).rights.modification = "unknown"), /modification is "unknown"/);
  productionCase("fails when web redistribution is unknown", (d) => {
    asset(d).rights.status = "unresolved"; // "cleared" with a non-allowed redistribution is itself a schema error
    asset(d).rights.webRuntimeRedistribution = "unknown";
  }, /webRuntimeRedistribution is "unknown"/);
  productionCase("fails when rights are not cleared", (d) => (asset(d).rights.status = "unresolved"), /rights status is "unresolved"/);
  productionCase("fails with an unresolved dependency", (d) => {
    asset(d).provenance.dependencies = [{ id: "texture-x", kind: "texture", description: "embedded texture", status: "unresolved" }];
  }, /1 unresolved dependency \(texture-x\)/);
  productionCase("fails with an unknown origin", (d) => (asset(d).provenance.origin = "unknown"), /provenance origin is "unknown"/);
  productionCase("fails while review is not approved", (d) => (asset(d).review = { status: "unreviewed", reviewedBy: null, reviewedAt: null }), /review status is "unreviewed"/);

  it("an approval without a named human reviewer, or without a review time, is refused", () => {
    // No stored bytes: only the approval itself is at stake.
    const approvalCodes = (review: Mutable) => {
      const a = fixtureAsset();
      a.usage = "production";
      a.review = { ...APPROVED_REVIEW, ...review };
      a.revisions["1"].artifact = null;
      return validateAssetRegistry({ schemaVersion: 1, assets: { [ID]: a } }).map((e) => e.code);
    };
    expect(approvalCodes({})).toEqual([]);
    expect(approvalCodes({ reviewedBy: null })).toEqual(["review-approval-unattributed"]);
    expect(approvalCodes({ reviewedBy: "" })).toContain("review-approval-unattributed");
    expect(approvalCodes({ reviewedBy: "   " })).toContain("review-approval-unattributed");
    expect(approvalCodes({ reviewedAt: null })).toEqual(["review-approval-unattributed"]);
    expect(approvalCodes({ reviewedAt: "yesterday" })).toContain("review-approval-unattributed");
    expect(approvalCodes({ reviewedAt: "2026-09-24" })).toContain("review-approval-unattributed");
    expect(approvalCodes({ reviewedAt: "2026-02-30T10:00:00Z" })).toContain("review-approval-unattributed");
    // Defence in depth: the production rule re-checks the attribution even without the schema pass.
    expect(productionBlockers({ ...asset(source(asProduction) as unknown as Draft), review: { status: "approved", reviewedBy: "  ", reviewedAt: null } })).toEqual([
      "the approval does not name a human reviewer and a review time",
    ]);
  });

  it("dependencies may be cleared or removed; complete metadata alone never makes an asset production", () => {
    expect(codesOf(source((d) => {
      asset(d).provenance.dependencies = [
        { id: "a", kind: "texture", description: "cleared texture", status: "cleared" },
        { id: "b", kind: "animation", description: "stripped clip", status: "removed" },
      ];
    }))).toEqual([]);
    // Fully cleared metadata with a tracer usage stays a tracer: nothing promotes it.
    const tracer = source(asClearedTracer);
    expect(codesOf(tracer)).toEqual([]);
    expect(spatialAssetWarnings(tracer).map((w) => w.code)).toContain("asset-internal-tracer");
    const approvedTracer = source((d) => {
      asset(d).review = { ...APPROVED_REVIEW };
    }) as unknown as Draft;
    expect(assetGate({ components: approvedTracer.scene.components, registry: approvedTracer.assets as AssetRegistry }).errors.map((e) => e.code)).toEqual(["asset-internal-tracer-unaccepted"]);
  });
});

describe("internal-tracer rule", () => {
  it("requires the explicit internal-tracer-accepted review (gate), which repo-public also demands (schema)", () => {
    for (const status of ["unreviewed", "approved"]) {
      const input = source((d) => {
        asClearedTracer(d);
        asset(d).review.status = status;
      }) as unknown as Draft;
      expect(assetGate({ components: input.scene.components, registry: input.assets as AssetRegistry }).errors.map((e) => e.code), status).toEqual(["asset-internal-tracer-unaccepted"]);
      expect(codesOf(input as unknown as SpatialSourceInput), status).toEqual(["repo-public-unreviewed"]);
    }
  });

  // Gate-level rules, independent of storage: run the gate on a registry that skips the schema's
  // repo-public publication check (which would otherwise refuse these rights first).
  const gateCodes = (mutate: (d: Draft) => void) => {
    const input = source((d) => {
      asClearedTracer(d);
      mutate(d);
    }) as unknown as Draft;
    return assetGate({ components: input.scene.components, registry: input.assets as AssetRegistry }).errors.map((e) => e.code);
  };

  it("refuses restricted rights (and restricted bytes can never be repo-public)", () => {
    expect(gateCodes((d) => (asset(d).rights.status = "restricted"))).toEqual(["asset-rights-restricted"]);
    expect(codesOf(source((d) => {
      asClearedTracer(d);
      asset(d).rights.status = "restricted";
    }))).toEqual(["repo-public-uncleared"]);
  });

  it("still fails on prohibited redistribution and on a rejected review", () => {
    expect(gateCodes((d) => {
      asset(d).rights.status = "unresolved";
      asset(d).rights.webRuntimeRedistribution = "prohibited";
    })).toEqual(["asset-redistribution-prohibited"]);
    expect(gateCodes((d) => (asset(d).review.status = "rejected"))).toEqual(["asset-review-rejected", "asset-internal-tracer-unaccepted"]);
    expect(codesOf(source((d) => (asset(d).review.status = "rejected")))).toEqual(["repo-public-unreviewed"]);
  });

  it("an uncleared tracer passes the gate only as a warned tracer — its bytes are what repo-public refuses", () => {
    expect(gateCodes((d) => {
      asset(d).rights.status = "unresolved";
      asset(d).provenance.dependencies = [{ id: "clip", kind: "animation", description: "third-party clip", status: "unresolved" }];
    })).toEqual([]);
  });
});

describe("repo-public rule — committing bytes to the public repository is publication", () => {
  it("refuses the original M1.0 tracer shape: internal tracer, unresolved rights and dependencies, repo-public bytes", () => {
    const input = source((d) => {
      asset(d).review = { status: "internal-tracer-accepted", reviewedBy: null, reviewedAt: null };
      Object.assign(asset(d).rights, { status: "unresolved", commercialUse: "unknown", webRuntimeRedistribution: "unknown", modification: "unknown" });
      asset(d).provenance.creationContext = "tutorial-assisted";
      asset(d).provenance.dependencies = [
        { id: "animation-third-party", kind: "animation", description: "embedded third-party clip", status: "unresolved" },
        { id: "texture-unknown", kind: "texture", description: "embedded texture of unknown origin", status: "unresolved" },
      ];
    });
    expect(codesOf(input)).toEqual(["repo-public-uncleared", "repo-public-unreviewed"]);
    expect(messagesOf(input)).toMatch(/rights status is "unresolved"; webRuntimeRedistribution is "unknown"; 2 unresolved dependencies/);
    expect(messagesOf(input)).toMatch(/does not name its human reviewer/);
  });

  it("applies to every repo-public revision, referenced or not, and to unknown origin", () => {
    expect(codesOf(source((d) => {
      asset(d).revisions["2"] = structuredClone(asset(d).revisions["1"]);
      asset(d).rights.status = "unresolved";
      asset(d).usage = "internal-tracer";
      asset(d).review = { status: "internal-tracer-accepted", reviewedBy: null, reviewedAt: null };
    })).filter((c) => c === "repo-public-uncleared")).toHaveLength(2);
    const unreferenced = source((d) => {
      d.assets.assets[OTHER_ID] = fixtureAsset(SHA, BYTES.length, OTHER_ID);
      asset(d, OTHER_ID).provenance.origin = "unknown";
      asset(d, OTHER_ID).usage = "internal-tracer";
    });
    expect(codesOf(unreferenced)).toEqual(["repo-public-uncleared"]);
    expect(publicationBlockers(asset(unreferenced as unknown as Draft, OTHER_ID))).toEqual(['provenance origin is "unknown"']);
  });

  it("a cleared asset is publishable", () => {
    expect(publicationBlockers(fixtureAsset())).toEqual([]);
    expect(publicationReviewBlockers(fixtureAsset())).toEqual([]);
  });
});

describe("public publication policy — production never repo-public; publication is an attributed human review", () => {
  it("refuses production usage on repo-public storage, however cleared and approved", () => {
    expect(codesOf(source(asProduction))).toEqual(["repo-public-production", "repo-public-unreviewed"]);
    expect(messagesOf(source(asProduction))).toMatch(/production art never uses repo-public storage/);
    // Every repo-public revision of a production asset is reported, referenced or not.
    expect(codesOf(source((d) => {
      asProduction(d);
      asset(d).revisions["2"] = structuredClone(asset(d).revisions["1"]);
    })).filter((c) => c === "repo-public-production")).toHaveLength(2);
    // A production record with no stored bytes is not a publication.
    const a = fixtureAsset();
    Object.assign(a, { usage: "production", review: { ...APPROVED_REVIEW } });
    a.revisions["1"].artifact = null;
    expect(validateAssetRegistry({ schemaVersion: 1, assets: { [ID]: a } })).toEqual([]);
  });

  it("needs the explicit internal-tracer-accepted review", () => {
    for (const status of ["unreviewed", "approved", "rejected"]) {
      expect(codesOf(source((d) => (asset(d).review.status = status))), status).toEqual(["repo-public-unreviewed"]);
    }
    expect(messagesOf(source((d) => (asset(d).review.status = "unreviewed")))).toMatch(/review status is "unreviewed" \(needs "internal-tracer-accepted"\)/);
  });

  it("needs a human reviewer name: null, empty and whitespace-only are refused", () => {
    expect(codesOf(source((d) => (asset(d).review.reviewedBy = null)))).toEqual(["repo-public-unreviewed"]);
    expect(codesOf(source((d) => (asset(d).review.reviewedBy = "")))).toEqual(["invalid-review", "repo-public-unreviewed"]);
    expect(codesOf(source((d) => (asset(d).review.reviewedBy = " \t ")))).toEqual(["invalid-review", "repo-public-unreviewed"]);
    expect(publicationReviewBlockers({ ...fixtureAsset(), review: { ...TRACER_REVIEW, reviewedBy: "  " } })).toEqual(["the review does not name its human reviewer (reviewedBy)"]);
  });

  it("needs a genuinely valid ISO 8601 review time", () => {
    expect(codesOf(source((d) => (asset(d).review.reviewedAt = null)))).toEqual(["repo-public-unreviewed"]);
    for (const at of ["yesterday", "2026-09-24", "2026-09-24T10:00:00", "2026-02-30T10:00:00Z", "2026-13-01T00:00Z", "2026-09-24T24:00Z", "2026-09-24T10:60Z", "2026-09-24T10:00:61Z", "2026-09-24T10:00+15:00"]) {
      expect(codesOf(source((d) => (asset(d).review.reviewedAt = at))), at).toEqual(["invalid-review", "repo-public-unreviewed"]);
    }
  });

  it("isReviewTimestamp accepts real calendar instants only", () => {
    for (const ok of ["2026-09-24T10:00:00-07:00", "2026-09-24T17:00Z", "2024-02-29T00:00:00.123Z", "2026-12-31T23:59:59+14:00"]) expect(isReviewTimestamp(ok), ok).toBe(true);
    for (const bad of ["2026-02-29T00:00Z", "2026-04-31T00:00Z", "2026-00-10T00:00Z", "2026-09-00T00:00Z", " 2026-09-24T10:00Z", 1727200000000, null]) expect(isReviewTimestamp(bad), String(bad)).toBe(false);
  });
});

describe("registry schema — strict and safe", () => {
  const registryCodes = (mutate: (a: Mutable, r: Mutable) => void) => {
    const registry = { schemaVersion: 1, assets: { [ID]: fixtureAsset() } } as Mutable;
    mutate(registry.assets[ID], registry);
    return validateAssetRegistry(registry).map((e) => e.code);
  };

  it("permits the unknown origin but validates creationContext against its vocabulary", () => {
    expect(registryCodes((a) => {
      a.provenance.origin = "unknown";
      a.revisions["1"].artifact = null; // no public bytes, so publication is not at stake
    })).toEqual([]);
    expect(registryCodes((a) => (a.provenance.creationContext = "tutorial-assisted"))).toEqual([]);
    expect(registryCodes((a) => delete a.provenance.creationContext)).toEqual([]);
    expect(registryCodes((a) => (a.provenance.creationContext = "made it myself mostly"))).toEqual(["invalid-provenance"]);
    expect(registryCodes((a) => (a.provenance.origin = "found online"))).toEqual(["invalid-provenance"]);
  });

  it("rejects a current revision that does not exist and a non-canonical revision key", () => {
    expect(registryCodes((a) => (a.currentRevision = 2))).toEqual(["invalid-revision"]);
    expect(registryCodes((a) => (a.currentRevision = 1.5))).toContain("invalid-revision");
    expect(registryCodes((a) => (a.revisions["01"] = structuredClone(a.revisions["1"])))).toEqual(["invalid-revision"]);
  });

  it("rejects malformed and path-traversing object keys, and cross-asset object-key reuse", () => {
    for (const key of ["../../../etc/passwd", "assets/art/../../secret.glb", `assets/art/${ID}.glb`, `/${KEY}`, KEY.toUpperCase(), `assets/art/nested/${ID}.${SHA.slice(0, 32)}.glb`]) {
      expect(registryCodes((a) => (a.revisions["1"].artifact.storage.objectKey = key)), key).toEqual(["invalid-object-key"]);
    }
    // The key embeds the asset id: a second asset cannot claim the first asset's bytes.
    expect(registryCodes((_a, r) => {
      r.assets[OTHER_ID] = fixtureAsset(SHA, BYTES.length, OTHER_ID);
      r.assets[OTHER_ID].revisions["1"].artifact.storage.objectKey = KEY;
    })).toEqual(["invalid-object-key"]);
  });

  it("rejects unsupported storage backends in the validator and the resolver", () => {
    for (const backend of ["s3", "__proto__", "Repo-Public"]) {
      expect(registryCodes((a) => (a.revisions["1"].artifact.storage = { backend, objectKey: "x" })), backend).toEqual(["unsupported-storage-backend"]);
      expect(() => runtimeAssetUrl({ backend, objectKey: "x" }), backend).toThrow(/unsupported storage backend/);
    }
  });

  it("keeps unexpected-field rejection and the id / digest / size shapes", () => {
    expect(registryCodes((a) => (a.url = "/x.glb"))).toEqual(["unexpected-field"]);
    expect(registryCodes((a) => (a.rights.cleared = true))).toEqual(["unexpected-field"]);
    expect(registryCodes((a) => (a.revisions["1"].artifact.sha256 = SHA.slice(0, 32)))).toContain("invalid-artifact");
    expect(registryCodes((a) => (a.revisions["1"].artifact.bytes = 0))).toContain("invalid-artifact");
    expect(registryCodes((a) => {
      a.rights.status = "cleared";
      a.rights.webRuntimeRedistribution = "unknown";
    })).toContain("invalid-rights");
    expect(registryCodes((_a, r) => (r.assets["Rock Monster"] = r.assets[ID]))).toContain("invalid-asset-id");
    expect(validateAssetRegistry(JSON.parse('{"schemaVersion":1,"assets":{"__proto__":{}}}')).map((e) => e.code)).toContain("invalid-asset-id");
  });
});

describe("storage contract — provider-neutral external content-addressed backend", () => {
  const EXTERNAL_KEY = `art/${ID}/${SHA}.glb`;
  const onExternal = (d: Draft) => (asset(d).revisions["1"].artifact.storage = { backend: "external-cas", objectKey: EXTERNAL_KEY });

  it("keys external objects by asset id + full SHA-256, exact match only", () => {
    expect(objectKeyFor("external-cas", ID, SHA, "glb")).toBe(EXTERNAL_KEY);
    expect(EXTERNAL_KEY).toMatch(EXTERNAL_CAS_OBJECT_KEY);
    const registryOf = (objectKey: string) => {
      const a = fixtureAsset();
      a.revisions["1"].artifact.storage = { backend: "external-cas", objectKey };
      return validateAssetRegistry({ schemaVersion: 1, assets: { [ID]: a } }).map((e) => e.code);
    };
    expect(registryOf(EXTERNAL_KEY)).toEqual([]);
    for (const key of [KEY, `art/${ID}/${SHA.slice(0, 32)}.glb`, `art/${OTHER_ID}/${SHA}.glb`, `/${EXTERNAL_KEY}`, `art/${ID}/../${SHA}.glb`]) {
      expect(registryOf(key), key).toEqual(["invalid-object-key"]);
    }
  });

  it("is where production art lives: a cleared, approved production asset validates in the registry", () => {
    const input = source((d) => {
      asProduction(d);
      onExternal(d);
    });
    expect(validateAssetRegistry(input.assets as unknown)).toEqual([]);
    // Not a Git publication: an unreviewed, uncleared record may be staged there (never referenced).
    const a = fixtureAsset();
    Object.assign(a, { review: { status: "unreviewed", reviewedBy: null, reviewedAt: null } });
    a.rights.status = "unresolved";
    a.revisions["1"].artifact.storage = { backend: "external-cas", objectKey: EXTERNAL_KEY };
    expect(validateAssetRegistry({ schemaVersion: 1, assets: { [ID]: a } })).toEqual([]);
  });

  it("cannot be referenced until its runtime resolution exists (adapter-pending), and the resolver refuses to guess", () => {
    const input = source((d) => {
      asProduction(d);
      onExternal(d);
    });
    expect(codesOf(input)).toEqual(["asset-storage-unresolved"]);
    expect(messagesOf(input)).toMatch(/adapter-pending/);
    expect(isRuntimeResolvable("external-cas")).toBe(false);
    expect(isRuntimeResolvable("repo-public")).toBe(true);
    expect(() => runtimeAssetUrl({ backend: "external-cas", objectKey: EXTERNAL_KEY })).toThrow(/adapter pending/);
    expect(STORAGE_BACKEND_CONTRACTS["external-cas"]).toMatchObject({ status: "adapter-pending", publishesToGit: false, allowsProduction: true });
    expect(STORAGE_BACKEND_CONTRACTS["repo-public"]).toMatchObject({ status: "implemented", publishesToGit: true, allowsProduction: false });
  });

  it("moving bytes between backends changes only storage — asset id and revision are untouched", () => {
    const repo = source();
    const external = source(onExternal);
    expect(Object.keys((external.assets as Mutable).assets)).toEqual(Object.keys((repo.assets as Mutable).assets));
    const [r, e] = [asset(repo as unknown as Draft).revisions["1"].artifact, asset(external as unknown as Draft).revisions["1"].artifact];
    expect({ ...e, storage: undefined }).toEqual({ ...r, storage: undefined });
  });
});

describe("duplicate keys at the registry read boundary", () => {
  it("finds repeated keys that JSON.parse would silently collapse, at any depth", () => {
    const text = `{"schemaVersion":1,"assets":{"${ID}":{"name":"a"},"${ID}":{"name":"b","revisions":{"1":{},"1":{}}}}}`;
    expect(Object.keys(JSON.parse(text).assets)).toHaveLength(1); // the limitation being guarded
    expect(findDuplicateJsonKeys(text)).toEqual([`/assets/${ID}`, `/assets/${ID}/revisions/1`]);
  });

  it("has no false positives for equal keys in sibling objects, arrays, or braces / quotes inside strings", () => {
    const text = JSON.stringify({ a: { x: 1 }, b: { x: 2 }, list: [{ x: 1 }, { x: 2 }], s: 'he said "{x}" \\ ] }', t: ["{", "}"] });
    expect(findDuplicateJsonKeys(text)).toEqual([]);
    expect(findDuplicateJsonKeys(JSON.stringify(source().assets, null, 2))).toEqual([]);
  });

  it("readAssetRegistry refuses a registry file with duplicate keys", () => {
    const dir = mkdtempSync(join(tmpdir(), "nrvnaverse-registry-"));
    try {
      const file = join(dir, "asset-registry.json");
      writeFileSync(file, `{"schemaVersion":1,"assets":{"${ID}":{},"${ID}":{}}}`);
      expect(() => readAssetRegistry(file)).toThrow(/repeats keys.*\/assets\/ast_fx7k2m9q4w8r3t6y/);
      writeFileSync(file, JSON.stringify(source().assets));
      expect(readAssetRegistry(file)).toEqual(source().assets);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("scene references", () => {
  it("fails a model component that uses a raw URL instead of the registry", () => {
    expect(codesOf(source((d) => {
      delete component(d).assetRef;
      component(d).url = "/assets/art/raw.glb";
    }))).toEqual(["unregistered-asset-url"]);
  });

  it("fails a component that declares both assetRef and url", () => {
    expect(codesOf(source((d) => (component(d).url = "/assets/art/raw.glb")))).toEqual(["asset-ref-with-url"]);
  });

  it("fails a malformed or unknown asset reference", () => {
    expect(codesOf(source((d) => (component(d).assetRef = "raw.glb")))).toEqual(["invalid-asset-ref"]);
    expect(codesOf(source((d) => (component(d).assetRef = OTHER_ID)))).toEqual(["unknown-asset-ref"]);
  });

  it("fails assetRef on a component type that cannot carry a runtime asset", () => {
    expect(codesOf(source((d) => {
      d.scene.components["path-east"].assetRef = ID;
    }))).toEqual(["asset-ref-unsupported-component"]);
    expect(codesOf(source((d) => (component(d).type = "Model")))).toEqual(["asset-ref-unsupported-component"]);
  });

  it("fails a missing registry and a referenced asset with no runtime artifact", () => {
    expect(codesOf(source((d) => (d.assets = null as unknown as Mutable)))).toEqual(["missing-asset-registry"]);
    expect(codesOf(source((d) => delete d.config.assetRegistry))).toEqual(["missing-asset-registry"]);
    expect(codesOf(source((d) => (asset(d).revisions["1"].artifact = null)))).toEqual(["asset-missing-artifact"]);
  });
});

describe("resolution — deterministic, content-addressed, stable for unrelated chunks", () => {
  const base = () => generateSpatialArtifacts(source());
  const plain = generateSpatialArtifacts(committed);

  it("replaces assetRef with the current revision's content-addressed URL in every artifact", () => {
    const gen = base();
    const model = JSON.parse(gen.files[gen.chunkFiles.hub]).components[COMPONENT];
    expect(model.assetRef).toBeUndefined();
    expect(model.url).toBe(`/${KEY}`);
    expect(model.url).toBe(`/assets/art/${ID}.${SHA.slice(0, 32)}.glb`);
    for (const text of Object.values(gen.files)) expect(text).not.toContain("assetRef");
    expect(gen.assetIds).toEqual([ID]);
  });

  it("a referenced asset changes only the chunk that holds it; the global scene and other chunks stay byte-identical", () => {
    const gen = base();
    expect(gen.chunkFiles.hub).not.toBe(plain.chunkFiles.hub);
    expect(gen.globalSceneFile).toBe(plain.globalSceneFile);
    for (const key of ["music", "fashion-culture", "cannabis-21"]) {
      expect(gen.chunkFiles[key], key).toBe(plain.chunkFiles[key]);
      expect(gen.files[gen.chunkFiles[key]]).toBe(plain.files[plain.chunkFiles[key]]);
    }
  });

  it("is deterministic; a rename or provenance-text edit changes nothing", () => {
    expect(generateSpatialArtifacts(source()).files).toEqual(base().files);
    expect(generateSpatialArtifacts(source((d) => (asset(d).name = "Renamed")))).toEqual(base());
    expect(generateSpatialArtifacts(source((d) => (asset(d).provenance.creator = "someone else")))).toEqual(base());
  });

  it("a new revision (new digest) is a new URL and a new Hub digest, keeps the asset id and moves nothing else", () => {
    const sha2 = createHash("sha256").update("revision 2").digest("hex");
    const revised = generateSpatialArtifacts(source((d) => {
      asset(d).revisions["2"] = fixtureAsset(sha2).revisions["1"];
      asset(d).currentRevision = 2;
    }));
    const b = base();
    expect(revised.chunkFiles.hub).not.toBe(b.chunkFiles.hub);
    expect(JSON.parse(revised.files[revised.chunkFiles.hub]).components[COMPONENT].url).toBe(`/assets/art/${ID}.${sha2.slice(0, 32)}.glb`);
    for (const key of ["music", "fashion-culture", "cannabis-21"]) expect(revised.chunkFiles[key]).toBe(b.chunkFiles[key]);
    expect(revised.globalSceneFile).toBe(b.globalSceneFile);
    expect(revised.assetIds).toEqual([ID]);
    // Rolling currentRevision back reproduces the original generation exactly.
    const rolledBack = generateSpatialArtifacts(source((d) => (asset(d).revisions["2"] = fixtureAsset(sha2).revisions["1"])));
    expect(rolledBack.files).toEqual(b.files);
  });

  it("leaves components without assetRef untouched (same object) and separates identity, revision and storage", () => {
    const components = { a: { id: "a", type: "mesh" } };
    expect(resolveAssetRefs(components, null).a).toBe(components.a);
    const artifact = fixtureAsset().revisions["1"].artifact;
    expect(Object.keys(artifact).sort()).toEqual(["bytes", "format", "sha256", "storage"]);
    expect(runtimeAssetUrl(artifact.storage)).toBe(`/${artifact.storage.objectKey}`);
    expect(artifact.storage.objectKey).toMatch(REPO_PUBLIC_OBJECT_KEY);
  });

  it("the M1 bands are warnings only: an asset far over every band still validates and generates", () => {
    const input = source((d) => {
      asset(d).revisions["1"].stats = { triangles: 10_000_000, maxTextureDimension: 16384 };
      asset(d).revisions["1"].artifact.bytes = BYTES.length; // bytes unchanged: the band is on the stats
    });
    expect(validateSpatialSource(input).ok).toBe(true);
    expect(() => generateSpatialArtifacts(input)).not.toThrow();
    expect(spatialAssetWarnings(input).map((w) => w.code)).toEqual(expect.arrayContaining(["m1-triangles", "m1-texture-dimension"]));
  });
});

describe("binary verification (cli, temp directory only)", () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "nrvnaverse-assets-"));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  const registry = (mutate?: (r: Mutable) => void): AssetRegistry => {
    const r = structuredClone(source().assets as unknown as Mutable);
    mutate?.(r);
    return r as AssetRegistry;
  };
  const place = (key: string, content: Buffer) => {
    const path = join(dir, ...key.split("/"));
    mkdirSync(join(path, ".."), { recursive: true });
    writeFileSync(path, content);
  };

  it("passes when the stored artifact matches the registry exactly", () => {
    place(KEY, BYTES);
    expect(checkRuntimeAssets(registry(), [ID], dir)).toEqual({ ok: true, problems: [] });
  });

  it("fails on a missing artifact", () => {
    expect(checkRuntimeAssets(registry(), [ID], dir).problems).toEqual([`missing runtime asset ${KEY} (${ID} revision 1)`]);
  });

  it("fails on a byte-count mismatch", () => {
    place(KEY, Buffer.concat([BYTES, Buffer.from("!")]));
    const problems = checkRuntimeAssets(registry(), [ID], dir).problems;
    expect(problems.some((p) => /bytes, registry says/.test(p))).toBe(true);
  });

  it("fails on a SHA-256 mismatch with the same byte count", () => {
    const tampered = Buffer.from(BYTES);
    tampered[tampered.length - 1] ^= 1;
    place(KEY, tampered);
    const problems = checkRuntimeAssets(registry(), [ID], dir).problems;
    expect(problems).toHaveLength(1);
    expect(problems[0]).toMatch(/has sha256 .*, registry says/);
  });

  it("fails on an orphan file and on the stale previous revision's file", () => {
    place(KEY, BYTES);
    place("assets/art/hand-copied.glb", BYTES);
    expect(checkRuntimeAssets(registry(), [ID], dir).problems).toEqual([
      "unexpected file assets/art/hand-copied.glb — not the current artifact of any referenced registered asset",
    ]);
    rmSync(join(dir, "assets", "art", "hand-copied.glb"));
    // Revision 2 becomes current: revision 1's file must be removed by the asset procedure.
    const bytes2 = Buffer.from("glTF synthetic revision 2");
    const sha2 = createHash("sha256").update(bytes2).digest("hex");
    const r2 = registry((r) => {
      r.assets[ID].revisions["2"] = fixtureAsset(sha2, bytes2.length).revisions["1"];
      r.assets[ID].currentRevision = 2;
    });
    place(repoPublicObjectKey(ID, sha2, "glb"), bytes2);
    expect(checkRuntimeAssets(r2, [ID], dir).problems).toEqual([
      `unexpected file ${KEY} — not the current artifact of any referenced registered asset`,
    ]);
  });

  it("fails on the file of a registered but unreferenced asset", () => {
    place(KEY, BYTES);
    expect(checkRuntimeAssets(registry(), [], dir).problems).toEqual([
      `unexpected file ${KEY} — not the current artifact of any referenced registered asset`,
    ]);
  });
});

describe("next.config.ts — content-addressed art cache policy", () => {
  const require = createRequire(import.meta.url);
  const { pathToRegexp } = require("next/dist/compiled/path-to-regexp") as { pathToRegexp: (source: string, keys: unknown[], opts: object) => RegExp };
  async function cacheControlFor(path: string): Promise<string[]> {
    const values: string[] = [];
    for (const rule of await deliveryHeaders()) {
      if (!pathToRegexp(rule.source, [], { strict: true, sensitive: false, delimiter: "/" }).test(path)) continue;
      for (const h of rule.headers) if (h.key === "Cache-Control") values.push(h.value);
    }
    return values;
  }

  it("serves a resolved content-addressed art URL as immutable", async () => {
    const gen = generateSpatialArtifacts(source());
    const url = JSON.parse(gen.files[gen.chunkFiles.hub]).components[COMPONENT].url;
    expect(await cacheControlFor(url)).toEqual([SPATIAL_IMMUTABLE_CACHE_CONTROL]);
    expect((await runtimeAssetHeaders()).map((r) => r.source)).toEqual(["/assets/art/:asset(ast_[0-9abcdefghjkmnpqrstvwxyz]{16}).:version([0-9a-f]{32}).glb"]);
  });

  it("does not make unhashed or malformed art, other /assets files or other formats immutable", async () => {
    const hex = "0123456789abcdef0123456789abcdef";
    for (const path of [
      "/assets/art/raw.glb",
      `/assets/art/${ID}.glb`,
      `/assets/art/${ID}.${hex.slice(0, 31)}.glb`,
      `/assets/art/${ID}.${hex}.gltf`,
      `/assets/art/${ID}.${hex}.glb.bak`,
      `/assets/art/ast_ILOU000000000000.${hex}.glb`,
      `/assets/art/nested/${ID}.${hex}.glb`,
      "/assets/anims/idle.json",
      `/assets/${ID}.${hex}.glb`,
    ]) {
      expect(await cacheControlFor(path), path).toEqual([]);
    }
  });
});
