// @ts-check
/**
 * Spatial data pipeline CLI (M0 Step 2B.1). Dependency-free Node ESM; run through the package
 * scripts `spatial:validate`, `spatial:generate`, `spatial:check`.
 *
 *   validate   validate spatial/source/* against the scene and the canonical destination set
 *   generate   validate, then (re)write the derived artifacts under public/data (only changed files)
 *              and remove stale CONTENT-ADDRESSED outputs of previous generations
 *   check      validate, then fail if any committed artifact is stale, missing or unexpected;
 *              additionally prints NON-FATAL initial M0 budget warnings (budgets.mjs: 64 KiB /
 *              64 components per runtime global-scene or chunk artifact — 2B.4C.2)
 *
 * Runtime assets (M1.0, assets.mjs): `generate` and `check` also verify every referenced asset's
 * current `repo-public` artifact byte-for-byte against the registry (size + full SHA-256) and fail on
 * any unregistered file under `public/assets/art/`; `check` prints the internal-tracer notices and
 * the M1 EXPERIMENTAL warning bands (never fatal). Runtime assets are placed by the asset pipeline,
 * never generated or deleted by this tool.
 *
 * Generated-output ownership (M0 Step 2B.4B.2). The global scene and every chunk are written under
 * content-addressed names (`spatial/global-scene.<token>.json`, `spatial/chunks/<key>.<token>.json`),
 * so a content change is a NEW file and the previous one becomes stale. `generate` therefore owns
 * the whole expected set: it writes exactly the current outputs and deletes any file that matches
 * the pipeline's content-addressed shapes (`isContentAddressedOutput`) but is not part of the
 * current generation. Nothing else is ever deleted — a file under `spatial/` or `spatial/chunks/`
 * that does not match those shapes (e.g. a legacy unversioned `chunks/<key>.json`, or anything
 * hand-placed) is reported as an unexpected leftover and left in place. `check` fails on stale,
 * missing and unexpected files alike, so nothing accumulates silently.
 *
 * File-system concerns live here; `pipeline.mjs` stays pure. The write / check / remove helpers
 * take an explicit output directory (defaulting to `public/data`) so the vitest suite can exercise
 * the generated-output lifecycle in a scratch directory without touching the committed artifacts.
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { REPO_PUBLIC_ART_PREFIX, currentRevision, formatAssetIssues } from "./assets.mjs";
import { formatSpatialBudgetWarning, spatialBudgetWarnings } from "./budgets.mjs";
import { OUTPUT, formatSpatialErrors, generateSpatialArtifacts, isContentAddressedOutput, spatialAssetWarnings, validateSpatialSource } from "./pipeline.mjs";

const APP_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

/** Authoritative physical source (hand-edited, committed). */
export const SOURCE_DIR = join(APP_ROOT, "spatial", "source");
export const SOURCE_CONFIG = join(SOURCE_DIR, "spatial-config.m0.json");
/** Canonical destination set — read only, generated by `@nrvnaverse/manifest`. */
export const DESTINATIONS_FILE = resolve(APP_ROOT, "../../packages/nrvna-manifest/generated/destinations.json");
/** Derived artifacts. Never edit by hand. */
export const OUTPUT_DIR = join(APP_ROOT, "public", "data");
/** Static root of the app; `repo-public` runtime assets live under `public/assets/art/` (M1.0). */
export const PUBLIC_DIR = join(APP_ROOT, "public");

const USAGE = `Usage: node scripts/spatial/cli.mjs <validate|generate|check>`;

/** @param {string} path */
function readJson(path) {
  return /** @type {unknown} */ (JSON.parse(readFileSync(path, "utf8")));
}

/** Read the authoritative source + the canonical destination set. */
export function loadSpatialSource() {
  const config = readJson(SOURCE_CONFIG);
  const sceneName = typeof config === "object" && config !== null && typeof (/** @type {any} */ (config).scene) === "string" ? /** @type {string} */ (/** @type {any} */ (config).scene) : "scene.m0.json";
  const scenePath = join(SOURCE_DIR, sceneName);
  if (!scenePath.startsWith(SOURCE_DIR + sep)) throw new Error(`scene reference escapes the source directory: ${sceneName}`);
  const scene = existsSync(scenePath) ? readJson(scenePath) : null;
  const destinations = readJson(DESTINATIONS_FILE);
  // Optional asset registry (M1.0), named by the config next to it. A declared but missing file is
  // reported by validation (`missing-asset-registry`), never silently ignored.
  const registryName = typeof config === "object" && config !== null ? /** @type {any} */ (config).assetRegistry : undefined;
  if (typeof registryName !== "string") return { config, scene, destinations };
  const registryPath = join(SOURCE_DIR, registryName);
  if (!registryPath.startsWith(SOURCE_DIR + sep)) throw new Error(`asset registry reference escapes the source directory: ${registryName}`);
  const assets = existsSync(registryPath) ? readJson(registryPath) : null;
  return { config, scene, destinations, assets };
}

/**
 * Binary side of the asset gate (M1.0): every referenced asset's current `repo-public` artifact must
 * exist under `public/` with exactly the registered byte count and full SHA-256, and every file in
 * `public/assets/art/` must be the current artifact of a registered asset (nothing unregistered or
 * stale ships). Runtime assets are never generated or deleted by this tool — they are placed by the
 * asset pipeline and verified here.
 * @param {import("./assets.mjs").AssetRegistry | null | undefined} registry
 * @param {string[]} referencedAssetIds
 * @param {string} publicDir
 * @returns {{ ok: boolean; problems: string[] }}
 */
export function checkRuntimeAssets(registry, referencedAssetIds, publicDir = PUBLIC_DIR) {
  /** @type {string[]} */
  const problems = [];
  /** @type {Set<string>} object keys that are allowed to exist */
  const expected = new Set();
  for (const assetId of referencedAssetIds) {
    const record = registry?.assets[assetId];
    const revision = record ? currentRevision(record) : null;
    const artifact = revision?.artifact;
    if (!artifact || artifact.storage.backend !== "repo-public") continue;
    expected.add(artifact.storage.objectKey);
    const path = join(publicDir, ...artifact.storage.objectKey.split("/"));
    if (!existsSync(path)) {
      problems.push(`missing runtime asset ${artifact.storage.objectKey} (${assetId} revision ${record?.currentRevision})`);
      continue;
    }
    const bytes = readFileSync(path);
    if (bytes.length !== artifact.bytes) problems.push(`runtime asset ${artifact.storage.objectKey} is ${bytes.length} bytes, registry says ${artifact.bytes}`);
    const sha256 = createHash("sha256").update(bytes).digest("hex");
    if (sha256 !== artifact.sha256) problems.push(`runtime asset ${artifact.storage.objectKey} has sha256 ${sha256}, registry says ${artifact.sha256}`);
  }
  const artDir = join(publicDir, ...REPO_PUBLIC_ART_PREFIX.split("/"));
  if (existsSync(artDir)) {
    for (const name of readdirSync(artDir).sort()) {
      const key = `${REPO_PUBLIC_ART_PREFIX}/${name}`;
      if (!expected.has(key)) problems.push(`unexpected file ${key} — not the current artifact of any referenced registered asset`);
    }
  }
  return { ok: problems.length === 0, problems };
}

/**
 * Line endings are normalised before comparison so a Git `core.autocrlf` checkout on Windows is
 * not reported as stale; the generator itself always writes LF.
 * @param {string} text
 */
function normalizeEol(text) {
  return text.replace(/\r\n/g, "\n");
}

/**
 * Every `.json` file currently in the generator's output namespace: the chunk directory (any
 * name) and `spatial/global-scene*.json`. Anything listed here that the current generation does
 * not produce is unexpected — a stale content version, a chunk removed from the source, or a
 * legacy unversioned name — and is reported; only content-addressed shapes are ever deleted.
 * @param {string} outputDir
 */
export function existingOutputCandidates(outputDir = OUTPUT_DIR) {
  /** @type {string[]} */
  const found = [];
  const chunksDir = join(outputDir, OUTPUT.chunksDir);
  if (existsSync(chunksDir)) {
    for (const name of readdirSync(chunksDir)) if (name.endsWith(".json")) found.push(`${OUTPUT.chunksDir}/${name}`);
  }
  const spatialDir = dirname(join(outputDir, OUTPUT.globalSceneBase));
  const globalBase = OUTPUT.globalSceneBase.slice(OUTPUT.globalSceneBase.lastIndexOf("/") + 1);
  if (existsSync(spatialDir)) {
    for (const name of readdirSync(spatialDir)) {
      if (name.startsWith(globalBase) && name.endsWith(".json")) found.push(relative(outputDir, join(spatialDir, name)).split(sep).join("/"));
    }
  }
  return found.sort();
}

/**
 * @param {Record<string, string>} files
 * @param {string} outputDir
 * @returns {{ written: string[]; unchanged: string[] }}
 */
export function writeArtifacts(files, outputDir = OUTPUT_DIR) {
  /** @type {{ written: string[]; unchanged: string[] }} */
  const result = { written: [], unchanged: [] };
  for (const [name, content] of Object.entries(files)) {
    const path = join(outputDir, name);
    const prev = existsSync(path) ? normalizeEol(readFileSync(path, "utf8")) : null;
    if (prev === content) {
      result.unchanged.push(name);
      continue;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf8");
    result.written.push(name);
  }
  return result;
}

/**
 * @param {Record<string, string>} files
 * @param {string} outputDir
 * @returns {{ upToDate: boolean; stale: string[]; unexpected: string[] }}
 */
export function checkArtifacts(files, outputDir = OUTPUT_DIR) {
  /** @type {string[]} */
  const stale = [];
  for (const [name, content] of Object.entries(files)) {
    const path = join(outputDir, name);
    const actual = existsSync(path) ? normalizeEol(readFileSync(path, "utf8")) : null;
    if (actual !== content) stale.push(name);
  }
  const unexpected = existingOutputCandidates(outputDir).filter((name) => !(name in files));
  return { upToDate: stale.length === 0 && unexpected.length === 0, stale, unexpected };
}

/**
 * Delete stale content-addressed outputs of previous generations (files whose name matches the
 * pipeline's own `<base>.<token>.json` shapes but which the current generation does not produce).
 * Unexpected files of any other shape are returned as `leftovers` and never touched.
 * @param {Record<string, string>} files the current generation
 * @param {string} outputDir
 * @returns {{ removed: string[]; leftovers: string[] }}
 */
export function removeStaleArtifacts(files, outputDir = OUTPUT_DIR) {
  /** @type {{ removed: string[]; leftovers: string[] }} */
  const result = { removed: [], leftovers: [] };
  for (const name of checkArtifacts(files, outputDir).unexpected) {
    if (isContentAddressedOutput(name)) {
      unlinkSync(join(outputDir, name));
      result.removed.push(name);
    } else {
      result.leftovers.push(name);
    }
  }
  return result;
}

/** @param {string} name */
function sizeOf(name) {
  const path = join(OUTPUT_DIR, name);
  return existsSync(path) ? Buffer.byteLength(normalizeEol(readFileSync(path, "utf8")), "utf8") : 0;
}

/** @param {string[]} argv */
function main(argv) {
  const command = argv[0];
  switch (command) {
    case "validate": {
      const result = validateSpatialSource(loadSpatialSource());
      if (!result.ok) {
        console.error(formatSpatialErrors(result.errors));
        return 1;
      }
      console.log(`spatial source valid (${relative(APP_ROOT, SOURCE_CONFIG)})`);
      return 0;
    }
    case "generate": {
      const source = loadSpatialSource();
      const artifacts = generateSpatialArtifacts(source);
      const assetCheck = checkRuntimeAssets(/** @type {any} */ (source.assets) ?? null, artifacts.assetIds);
      if (!assetCheck.ok) {
        console.error(assetCheck.problems.join("\n"));
        return 1;
      }
      const { written, unchanged } = writeArtifacts(artifacts.files);
      // Write first, remove second: a failed write leaves the previous generation intact.
      const { removed, leftovers } = removeStaleArtifacts(artifacts.files);
      /** @param {string} name */
      const describe = (name) => `${name} (${sizeOf(name)} bytes${name in artifacts.versions ? `, content-addressed` : ""})`;
      for (const name of written) console.log(`wrote ${describe(name)}`);
      for (const name of unchanged) console.log(`unchanged ${describe(name)}`);
      for (const name of removed) console.log(`removed stale ${name} (previous content version)`);
      for (const name of leftovers) console.warn(`unexpected leftover ${name} — not generated from the current source and not a content-addressed output; delete it by hand`);
      console.log(`${artifacts.chunkKeys.length} chunks, ${artifacts.destinationIds.length} destination placements`);
      return leftovers.length === 0 ? 0 : 1;
    }
    case "check": {
      const source = loadSpatialSource();
      const artifacts = generateSpatialArtifacts(source);
      const assetCheck = checkRuntimeAssets(/** @type {any} */ (source.assets) ?? null, artifacts.assetIds);
      if (!assetCheck.ok) {
        console.error(assetCheck.problems.join("\n"));
        return 1;
      }
      const { upToDate, stale, unexpected } = checkArtifacts(artifacts.files);
      if (!upToDate) {
        if (stale.length) console.error(`stale generated files: ${stale.join(", ")}`);
        if (unexpected.length) console.error(`unexpected files (stale content versions, removed chunks or legacy names): ${unexpected.join(", ")}`);
        console.error(`run "pnpm --filter the-nrvnaverse spatial:generate" and commit the result`);
        return 1;
      }
      // Runtime assets (M1.0): internal-tracer notices and M1 EXPERIMENTAL warning bands — never fatal.
      const assetWarnings = spatialAssetWarnings(source);
      if (assetWarnings.length) console.warn(formatAssetIssues(assetWarnings));
      if (artifacts.assetIds.length) console.log(`runtime assets verified: ${artifacts.assetIds.join(", ")} (registry digest + bytes match the stored artifact)`);
      // Initial M0 warning budgets (2B.4C.2): reported, never fatal — see budgets.mjs.
      const warnings = spatialBudgetWarnings(artifacts);
      for (const warning of warnings) console.warn(formatSpatialBudgetWarning(warning));
      console.log(`generated spatial artifacts up to date (${Object.keys(artifacts.files).length} files${warnings.length ? `, ${warnings.length} budget warning${warnings.length === 1 ? "" : "s"}` : ", within initial budgets"})`);
      return 0;
    }
    case "--help":
    case "-h":
    case undefined:
      console.log(USAGE);
      return command === undefined ? 1 : 0;
    default:
      console.error(`Unknown command: ${command}\n\n${USAGE}`);
      return 1;
  }
}

// Run only when executed directly (`node scripts/spatial/cli.mjs …`); importing the module (tests) has no side effect.
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    process.exitCode = main(process.argv.slice(2));
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exitCode = 1;
  }
}
