// @ts-check
/**
 * Spatial data pipeline CLI (M0 Step 2B.1). Dependency-free Node ESM; run through the package
 * scripts `spatial:validate`, `spatial:generate`, `spatial:check`.
 *
 *   validate   validate spatial/source/* against the scene and the canonical destination set
 *   generate   validate, then (re)write the derived artifacts under public/data (only changed files)
 *   check      validate, then fail if any committed artifact is stale, missing or unexpected
 *
 * File-system concerns live here; `pipeline.mjs` stays pure and is what the tests exercise.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { OUTPUT, formatSpatialErrors, generateSpatialArtifacts, validateSpatialSource } from "./pipeline.mjs";

const APP_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

/** Authoritative physical source (hand-edited, committed). */
export const SOURCE_DIR = join(APP_ROOT, "spatial", "source");
export const SOURCE_CONFIG = join(SOURCE_DIR, "spatial-config.m0.json");
/** Canonical destination set — read only, generated by `@nrvnaverse/manifest`. */
export const DESTINATIONS_FILE = resolve(APP_ROOT, "../../packages/nrvna-manifest/generated/destinations.json");
/** Derived artifacts. Never edit by hand. */
export const OUTPUT_DIR = join(APP_ROOT, "public", "data");

const USAGE = `Usage: node scripts/spatial/cli.mjs <validate|generate|check>`;

/** @param {string} path */
function readJson(path) {
  return /** @type {unknown} */ (JSON.parse(readFileSync(path, "utf8")));
}

/** Read the authoritative source + the canonical destination set. */
export function loadSpatialSource() {
  const config = readJson(SOURCE_CONFIG);
  const sceneName = typeof config === "object" && config !== null && typeof (/** @type {any} */ (config).scene) === "string" ? /** @type {string} */ (/** @type {any} */ (config).scene) : "scene.m0.json";
  const scenePath = join(SOURCE_DIR, sceneName);
  if (!scenePath.startsWith(SOURCE_DIR + sep)) throw new Error(`scene reference escapes the source directory: ${sceneName}`);
  const scene = existsSync(scenePath) ? readJson(scenePath) : null;
  const destinations = readJson(DESTINATIONS_FILE);
  return { config, scene, destinations };
}

/**
 * Line endings are normalised before comparison so a Git `core.autocrlf` checkout on Windows is
 * not reported as stale; the generator itself always writes LF.
 * @param {string} text
 */
function normalizeEol(text) {
  return text.replace(/\r\n/g, "\n");
}

/**
 * Every file currently under the chunk output directory, so a chunk removed from the source is
 * reported as an unexpected leftover instead of silently lingering.
 */
function existingChunkFiles() {
  const dir = join(OUTPUT_DIR, OUTPUT.chunksDir);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((name) => name.endsWith(".json"))
    .map((name) => `${OUTPUT.chunksDir}/${name}`);
}

/**
 * @param {Record<string, string>} files
 * @returns {{ written: string[]; unchanged: string[] }}
 */
export function writeArtifacts(files) {
  /** @type {{ written: string[]; unchanged: string[] }} */
  const result = { written: [], unchanged: [] };
  for (const [name, content] of Object.entries(files)) {
    const path = join(OUTPUT_DIR, name);
    const prev = existsSync(path) ? normalizeEol(readFileSync(path, "utf8")) : null;
    if (prev === content) {
      result.unchanged.push(name);
      continue;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf8");
    result.written.push(name);
  }
  return result;
}

/**
 * @param {Record<string, string>} files
 * @returns {{ upToDate: boolean; stale: string[]; unexpected: string[] }}
 */
export function checkArtifacts(files) {
  /** @type {string[]} */
  const stale = [];
  for (const [name, content] of Object.entries(files)) {
    const path = join(OUTPUT_DIR, name);
    const actual = existsSync(path) ? normalizeEol(readFileSync(path, "utf8")) : null;
    if (actual !== content) stale.push(name);
  }
  const unexpected = existingChunkFiles().filter((name) => !(name in files));
  return { upToDate: stale.length === 0 && unexpected.length === 0, stale, unexpected };
}

/** @param {string} name */
function sizeOf(name) {
  const path = join(OUTPUT_DIR, name);
  return existsSync(path) ? Buffer.byteLength(normalizeEol(readFileSync(path, "utf8")), "utf8") : 0;
}

/** @param {string[]} argv */
function main(argv) {
  const command = argv[0];
  switch (command) {
    case "validate": {
      const result = validateSpatialSource(loadSpatialSource());
      if (!result.ok) {
        console.error(formatSpatialErrors(result.errors));
        return 1;
      }
      console.log(`spatial source valid (${relative(APP_ROOT, SOURCE_CONFIG)})`);
      return 0;
    }
    case "generate": {
      const artifacts = generateSpatialArtifacts(loadSpatialSource());
      const { written, unchanged } = writeArtifacts(artifacts.files);
      for (const name of written) console.log(`wrote ${name} (${sizeOf(name)} bytes)`);
      for (const name of unchanged) console.log(`unchanged ${name} (${sizeOf(name)} bytes)`);
      const leftovers = checkArtifacts(artifacts.files).unexpected;
      for (const name of leftovers) console.warn(`unexpected leftover ${name} — delete it (not generated from the current source)`);
      console.log(`${artifacts.chunkKeys.length} chunks, ${artifacts.destinationIds.length} destination placements`);
      return leftovers.length === 0 ? 0 : 1;
    }
    case "check": {
      const artifacts = generateSpatialArtifacts(loadSpatialSource());
      const { upToDate, stale, unexpected } = checkArtifacts(artifacts.files);
      if (!upToDate) {
        if (stale.length) console.error(`stale generated files: ${stale.join(", ")}`);
        if (unexpected.length) console.error(`unexpected files: ${unexpected.join(", ")}`);
        console.error(`run "pnpm --filter the-nrvnaverse spatial:generate" and commit the result`);
        return 1;
      }
      console.log(`generated spatial artifacts up to date (${Object.keys(artifacts.files).length} files)`);
      return 0;
    }
    case "--help":
    case "-h":
    case undefined:
      console.log(USAGE);
      return command === undefined ? 1 : 0;
    default:
      console.error(`Unknown command: ${command}\n\n${USAGE}`);
      return 1;
  }
}

try {
  process.exitCode = main(process.argv.slice(2));
} catch (err) {
  console.error(err instanceof Error ? err.message : String(err));
  process.exitCode = 1;
}
